### ISSUE TITLE
Notes on standard .travis.yml file compenets

### ISSUE THREAD

**Issue by kevina** [ipfs/ci-helpers#2]
Most but not all the existing `.travis.yml` have this:
```
cache:
  directories:
    - $GOPATH/src/gx

notifications:
  email: false
```
If there where there I left it, if not, I didn't add it (for the most part).

Also some projects have:

```
sudo: false
```
I left this one alone, but wondering why some have it and not others.  The projects that have it in libp2p:
```
./go-libp2p-pnet/.travis.yml:sudo: false
./go-libp2p-netutil/.travis.yml:sudo: false
./go-peerstream/.travis.yml:sudo: false
./go-libp2p-swarm/.travis.yml:sudo: false
./go-libp2p-transport/.travis.yml:sudo: false
./go-ws-transport/.travis.yml:sudo: false
./go-libp2p-crypto/.travis.yml:sudo: true
./go-testutil/.travis.yml:sudo: false
./go-libp2p-peer/.travis.yml:sudo: false
./go-libp2p-secio/.travis.yml:sudo: false
./go-libp2p-loggables/.travis.yml:sudo: false
./go-reuseport/.travis.yml:sudo: false
```

**Comment by Stebalien** [comment]
Use `sudo: false` as much as possible. If it passes with `sudo: false`, use it. With sudo, we can use a container (fast), without sudo, we have to use a VM (slow).

Everything else looks good.

**Comment by kevina** [comment]
@Stebalien okay I will go back though and add sudo:false and make a note when it fails.

**Comment by kevina** [comment]
Concerning email, I actually find it useful, but i agree in the way Travis handles it is annoying.   We should probably be consist in our config files.  Should I add
```
notifications:
  email: false
```
If it was not there already.  Also, probably less important.  Should I add the other bit if it was not already there:
```
cache:
  directories:
    - $GOPATH/src/gx
```
cc @Stebalien @whyrusleeping

**Comment by Kubuxu** [comment]
Yes , add the cache and emails.

**Comment by whyrusleeping** [comment]
Yeah, i would disable the emails, and add in caching. Caching the gx directories will save us a lot of time.

**Comment by kevina** [comment]
Okay I added those two components if they where no already there.
