### ISSUE TITLE
gofmt

### ISSUE THREAD

**Issue by Kubuxu** [ipfs/ci-helpers#6]
It would be nice to also fail tests if `go fmt ./...` lists any files as being modified (formatted).

**Comment by kevina** [comment]
How about `find . -name '*.go' -print0 | xargs -0 gofmt -l` so that we don't actually modify any files.

Is there some code go code we should avoid running the gofmt check on?

**Comment by Kubuxu** [comment]
In go-ipfs we run go fmt over all code but we might want to exclude `/vendor/` for "reasons".

**Comment by Stebalien** [comment]
> How about find . -name '*.go' -print0 | xargs -0 gofmt -l so that we don't actually modify any files.

SGTM.

> Is there some code go code we should avoid running the gofmt check on?

Not that I can think of. However, we *may* run into issues with `gx-go rw` and gofmt. I'm not sure.

**Comment by Stebalien** [comment]
Hm. Do we need to run this pre-install?

**Comment by kevina** [comment]
I don't like the idea of having to do this pre-install and not in the test script.

We could check out a clean copy in a tmpdir and run `go fmt` there...

**Comment by Stebalien** [comment]
> I don't like the idea of having to do this pre-install and not in the test script.

I agree.

> We could check out a clean copy in a tmpdir and run 

Yuck but..., yes? I can't think of a better solution (it would also help us avoid any other contamination).

**Comment by kevina** [comment]
Yeah I think something like
```
GITDIR="$(pwd)"
cd "$(mktemp -d)"
git checkout --git-dir="$GITDIR"/.git
go fmt ./...
````
will work

**Comment by Stebalien** [comment]
SGTM.

**Comment by kevina** [comment]
This is now done, but I had to use `git clone -s`.
